### ISSUE TITLE
command line option `-o` is wrongly named

### ISSUE THREAD

**Issue by schmir** [trustlines-network/contract-deploy-tools#19]
I would prefer the command line option `-o` to be either removed or if we really need a short option to be replaced with `-O`.
Some folks may expect it to mean 'output file'. It's being used like that in `solc` and `gcc` (it's output directory in `solc`). `gcc` uses `-O` to turn on optimizations.

My recommendation would be to just go with the long option `--optimize`, which is also the option `solc` takes.

**Comment by berndbohmeier** [comment]
woops, yeah I meant to use `O` like gcc. So should we use `o` for what we use `d` right now?
And I'm fine with just having the long option.

**Comment by schmir** [comment]
The `-d` argument contains sources, not some kind of output. So, no, don't use it instead of `-d`(unless I miss something)

**Comment by berndbohmeier** [comment]
Ahm, yes that was stupid, I meant the option to specify where we want to save the output(at the moment defaults to `build/ceontracts.json`)

**Comment by schmir** [comment]
> This should be `-o` then?

yes
